version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: go-carballo/tenpo:latest
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tenpodb
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - CACHE_PERCENTAGE_URL=CACHE_PERCENTAGE_URL=https://a6530118-93ae-4994-9512-73735a03c189.mock.pstmn.io/percentage
    env_file: src/main/resources/application.properties
    ports:
      - "8080:8080"
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: tenpodb
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
  redis:
    image: redis:latest
    container_name: redis
